language: "en" # Supported languages -> hu, de, en, tr, es

database:
  type: "sqlite" # Supported database types -> sqlite, mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "coma112"
    username: "root"
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000
  mongodb:
    host: "localhost"
    port: 27017
    database: "bounty"
    username: ""
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    poolsize: 10
    lifetime: 1800

# With this you can modify in the placeholders the yes and no text.
placeholder:
  yes: "&aYes"
  no: "&cNo"

# You can turn off and on dependencies.
# You can set the min and max value for each dependency.
dependency:
  tokenmanager:
    enabled: false
    min: 0
    max: 0
  playerpoints:
    enabled: false
    min: 0
    max: 0
  level:
    enabled: true
    min: 0
    max: 0
  coinsengine:
    enabled: true
    min: 0
    max: 0
    currency: "coins"
#Vault:
  Money:
    min: 0
    max: 0

# This is the bounty item in the GUI.
bounty-item:
  amount: 1
  material: "PAPER"
  name: "&c&l! &6{target} &8(&7{id}&8) &c&l!"
  lore:
    - ""
    - "&6Sender: &f{player} &c⚡"
    - "&6Reward: &f{reward} &c⚡"
    - "&6Reward Type: &f{reward_type} &c⚡"
    - "&6Streak: &f{streak} &c🔥"

bountyfinder-item:
  amount: 1
  material: "COMPASS"
  name: "&e&lBOUNTYFINDER"
  lore:
    - ""
    - "&eHold this item in your hand,"
    - "&eto see which bounty is closest to you"

# This shows maximum values for methods. Like: maximum toplist to get is 15 so you can only get the 15th toplist.
# bounty-per-player -> Maximum bounty a player can set.
max:
  top-to-get: 15
  bounty-per-player: 5

# Menu Configuration
menu:
  title: "&6&lBOUNTIES"
  size: 54
  update-tick: 2
  back-item:
    amount: 1
    material: "RED_STAINED_GLASS"
    name: "&cBack"
    slot: 45
  forward-item:
    amount: 1
    material: "GREEN_STAINED_GLASS"
    name: "&aForward"
    slot: 53

# Features
# glowing.enabled -> You can enable and disable the glowing feature for the bounties.
# glowing.color -> If the glowing.enabled is true then you can set a custom glowing color.

# random-bounty.enabled -> You can enable and disable the random bounty feature.
# random-bounty.rewardType -> You can set reward types so that the type is the same when the random bounty is run
# random-bounty.reward -> The reward (int) with the rewardType
# random-bounty.per-second -> Shows how many seconds to set a random bounty
# random-bounty.player-value -> You can specify how to show the random bounty in the GUI

# bountyfinder.no-bounty-nearby -> The message to show when there is no bounty nearby
# bountyfinder.nearest-bounty -> The message to show when there is a bounty nearby

feature:
  glowing:
    enabled: true
    color: "RED"
  random-bounty:
    enabled: false
    rewardType: "TOKEN"
    reward: 50
    per-second: 7200
    player-value: "CONSOLE"
  bountyfinder:
    no-bounty-nearby: "&cNo bounties nearby"
    nearest-bounty: "&a{bounty} &8| &a{distance}m"

# Webhook
# webhook.enabled -> You can enable and disable the webhook feature
# webhook.url -> Discord Webhook URL
# webhook.random-sender -> The value if the bounty setter is random (by the random bounty feature)

webhook:
  enabled: false
  url: "WEBHOOK URL HERE!!!"
  bounty-death-embed:
    title: "BOUNTY TARGET DEATH"
    description: "{killer} killed {target} for {reward} {rewardType}"
    color: "ORANGE"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CBOUNTY"
    footer-icon: ""
    thumbnail: ""
    image: ""
  bounty-create-embed:
    title: "NEW BOUNTY"
    description: "{sender} has put a bounty on {target}'s head ({reward} {rewardType})"
    color: "ORANGE"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CBOUNTY"
    footer-icon: ""
    thumbnail: ""
    image: ""
  bounty-remove-embed:
    title: "REMOVED BOUNTY"
    description: "{target}'s bounty has been removed!"
    color: "ORANGE"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CBOUNTY"
    footer-icon: ""
    thumbnail: ""
    image: ""
  random-sender: "UNKNOWN"
