name: CBounty
version: '3.8.9'
main: coma112.cbounty.CBounty
api-version: '1.18'
folia-supported: true
authors:
  - Coma112
  - B3rcyy
  - Vulcan Studio
softdepend:
  - TokenManager
  - PlayerPoints
  - Vault
  - CoinsEngine
